{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ANEMO import ANEMO\n",
    "from ANEMO.edfreader import read_edf\n",
    "import pickle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "sujets = ['AM','BMC','CS','DC','FM','IP','LB','OP','RS','SR','TN','YK']\n",
    "times = ['2017-10-23_100057','2017-09-26_095637', '2017-10-03_134421','2017-09-27_161040',\n",
    "        '2017-10-03_143803','2017-09-28_115250', '2017-09-20_151043','2017-10-26_121823',\n",
    "        '2017-11-08_094717','2017-11-16_153313', '2017-11-08_150410','2017-11-17_172706']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "def fit(s) :\n",
    "    print(sujets[s])\n",
    "    \n",
    "    with open('data/enregistrement_%s_%s.pkl'%(sujets[s], times[s]), 'rb') as fichier :\n",
    "        exp = pickle.load(fichier, encoding='latin1')\n",
    "\n",
    "    datafile = 'data/enregistrement_%s_%s.asc'%(sujets[s], times[s])\n",
    "    data = read_edf(datafile, 'TRIALID')\n",
    "\n",
    "    Fit = ANEMO.Fit(exp)\n",
    "    \n",
    "    param_fit = Fit.Fit_full(data, equation='fct_velocity', plot=None,\n",
    "                             filt='velocity', cutoff=30,  fig_width=10, t_label=15, t_text=12,\n",
    "                             file_fig='figures/Fit_fct_velocity_filt_velo_30_%s'%sujets[s])\n",
    "\n",
    "    with open('parametre/param_Fit_%s_fct_velocity_filt_velo_30.pkl'%sujets[s], 'wb') as fichier:\n",
    "        f = pickle.Pickler(fichier)\n",
    "        f.dump(param_fit)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "DC\n",
      "block, trial =  0 0\n",
      "block, trial =  0 1\n",
      "block, trial =  0 2\n",
      "block, trial =  0 3\n",
      "block, trial =  0 4\n",
      "block, trial =  0 5\n",
      "block, trial =  0 6\n",
      "block, trial =  0 7\n",
      "block, trial =  0 8\n",
      "block, trial =  0 9\n",
      "block, trial =  0 10\n",
      "block, trial =  0 11\n",
      "block, trial =  0 12\n",
      "block, trial =  0 13\n",
      "block, trial =  0 14\n",
      "block, trial =  0 15\n",
      "block, trial =  0 16\n",
      "block, trial =  0 17\n",
      "block, trial =  0 18\n",
      "block, trial =  0 19\n",
      "block, trial =  0 20\n",
      "block, trial =  0 21\n",
      "block, trial =  0 22\n",
      "block, trial =  0 23\n",
      "block, trial =  0 24\n",
      "block, trial =  0 25\n",
      "block, trial =  0 26\n",
      "block, trial =  0 27\n",
      "block, trial =  0 28\n",
      "block, trial =  0 29\n",
      "block, trial =  0 30\n",
      "block, trial =  0 31\n",
      "block, trial =  0 32\n",
      "block, trial =  0 33\n",
      "block, trial =  0 34\n",
      "block, trial =  0 35\n",
      "block, trial =  0 36\n",
      "block, trial =  0 37\n",
      "block, trial =  0 38\n",
      "block, trial =  0 39\n",
      "block, trial =  0 40\n",
      "block, trial =  0 41\n",
      "block, trial =  0 42\n",
      "block, trial =  0 43\n",
      "block, trial =  0 44\n",
      "block, trial =  0 45\n",
      "block, trial =  0 46\n",
      "block, trial =  0 47\n",
      "block, trial =  0 48\n",
      "block, trial =  0 49\n",
      "block, trial =  0 50\n",
      "block, trial =  0 51\n",
      "block, trial =  0 52\n",
      "block, trial =  0 53\n",
      "block, trial =  0 54\n",
      "block, trial =  0 55\n",
      "block, trial =  0 56\n",
      "block, trial =  0 57\n",
      "block, trial =  0 58\n",
      "block, trial =  0 59\n",
      "block, trial =  0 60\n",
      "block, trial =  0 61\n",
      "block, trial =  0 62\n",
      "block, trial =  0 63\n",
      "block, trial =  0 64\n",
      "block, trial =  0 65\n",
      "block, trial =  0 66\n",
      "block, trial =  0 67\n",
      "block, trial =  0 68\n",
      "block, trial =  0 69\n",
      "block, trial =  0 70\n",
      "block, trial =  0 71\n",
      "block, trial =  0 72\n",
      "block, trial =  0 73\n",
      "block, trial =  0 74\n",
      "block, trial =  0 75\n",
      "block, trial =  0 76\n",
      "block, trial =  0 77\n",
      "block, trial =  0 78\n",
      "block, trial =  0 79\n",
      "block, trial =  0 80\n",
      "block, trial =  0 81\n",
      "block, trial =  0 82\n",
      "block, trial =  0 83\n",
      "block, trial =  0 84\n",
      "block, trial =  0 85\n",
      "block, trial =  0 86\n",
      "block, trial =  0 87\n",
      "block, trial =  0 88\n",
      "block, trial =  0 89\n",
      "block, trial =  0 90\n",
      "block, trial =  0 91\n",
      "block, trial =  0 92\n",
      "block, trial =  0 93\n",
      "block, trial =  0 94\n",
      "block, trial =  0 95\n",
      "block, trial =  0 96\n",
      "block, trial =  0 97\n",
      "block, trial =  0 98\n",
      "block, trial =  0 99\n",
      "block, trial =  0 100\n",
      "block, trial =  0 101\n",
      "block, trial =  0 102\n",
      "block, trial =  0 103\n",
      "block, trial =  0 104\n",
      "block, trial =  0 105\n",
      "block, trial =  0 106\n",
      "block, trial =  0 107\n",
      "block, trial =  0 108\n",
      "block, trial =  0 109\n",
      "block, trial =  0 110\n",
      "block, trial =  0 111\n",
      "block, trial =  0 112\n",
      "block, trial =  0 113\n",
      "block, trial =  0 114\n",
      "block, trial =  0 115\n",
      "block, trial =  0 116\n",
      "block, trial =  0 117\n",
      "block, trial =  0 118\n",
      "block, trial =  0 119\n",
      "block, trial =  0 120\n",
      "block, trial =  0 121\n",
      "block, trial =  0 122\n",
      "block, trial =  0 123\n",
      "block, trial =  0 124\n",
      "block, trial =  0 125\n",
      "block, trial =  0 126\n",
      "block, trial =  0 127\n",
      "block, trial =  0 128\n",
      "block, trial =  0 129\n",
      "block, trial =  0 130\n",
      "block, trial =  0 131\n",
      "block, trial =  0 132\n",
      "block, trial =  0 133\n",
      "block, trial =  0 134\n",
      "block, trial =  0 135\n",
      "block, trial =  0 136\n",
      "block, trial =  0 137\n",
      "block, trial =  0 138\n",
      "block, trial =  0 139\n",
      "block, trial =  0 140\n",
      "block, trial =  0 141\n",
      "block, trial =  0 142\n",
      "block, trial =  0 143\n",
      "block, trial =  0 144\n",
      "block, trial =  0 145\n",
      "block, trial =  0 146\n",
      "block, trial =  0 147\n",
      "block, trial =  0 148\n",
      "block, trial =  0 149\n",
      "block, trial =  0 150\n",
      "block, trial =  0 151\n",
      "block, trial =  0 152\n",
      "block, trial =  0 153\n",
      "block, trial =  0 154\n",
      "block, trial =  0 155\n",
      "block, trial =  0 156\n",
      "block, trial =  0 157\n",
      "block, trial =  0 158\n",
      "block, trial =  0 159\n",
      "block, trial =  0 160\n",
      "block, trial =  0 161\n",
      "block, trial =  0 162\n",
      "block, trial =  0 163\n",
      "block, trial =  0 164\n",
      "block, trial =  0 165\n",
      "block, trial =  0 166\n",
      "block, trial =  0 167\n",
      "block, trial =  0 168\n",
      "block, trial =  0 169\n",
      "block, trial =  0 170\n",
      "block, trial =  0 171\n",
      "block, trial =  0 172\n",
      "block, trial =  0 173\n",
      "block, trial =  0 174\n",
      "block, trial =  0 175\n",
      "block, trial =  0 176\n",
      "block, trial =  0 177\n",
      "block, trial =  0 178\n",
      "block, trial =  0 179\n",
      "block, trial =  0 180\n",
      "block, trial =  0 181\n",
      "block, trial =  0 182\n",
      "block, trial =  0 183\n",
      "block, trial =  0 184\n",
      "block, trial =  0 185\n",
      "block, trial =  0 186\n",
      "block, trial =  0 187\n",
      "block, trial =  0 188\n",
      "block, trial =  0 189\n",
      "block, trial =  0 190\n",
      "block, trial =  0 191\n",
      "block, trial =  0 192\n",
      "block, trial =  0 193\n",
      "block, trial =  0 194\n",
      "block, trial =  0 195\n",
      "block, trial =  0 196\n",
      "block, trial =  0 197\n",
      "block, trial =  0 198\n",
      "block, trial =  0 199\n",
      "block, trial =  1 0\n",
      "block, trial =  1 1\n",
      "block, trial =  1 2\n",
      "block, trial =  1 3\n",
      "block, trial =  1 4\n",
      "block, trial =  1 5\n",
      "block, trial =  1 6\n",
      "block, trial =  1 7\n",
      "block, trial =  1 8\n",
      "block, trial =  1 9\n",
      "block, trial =  1 10\n",
      "block, trial =  1 11\n",
      "block, trial =  1 12\n",
      "block, trial =  1 13\n",
      "block, trial =  1 14\n",
      "block, trial =  1 15\n",
      "block, trial =  1 16\n",
      "block, trial =  1 17\n",
      "block, trial =  1 18\n",
      "block, trial =  1 19\n",
      "block, trial =  1 20\n",
      "block, trial =  1 21\n",
      "block, trial =  1 22\n",
      "block, trial =  1 23\n",
      "block, trial =  1 24\n",
      "block, trial =  1 25\n",
      "block, trial =  1 26\n",
      "block, trial =  1 27\n",
      "block, trial =  1 28\n",
      "block, trial =  1 29\n",
      "block, trial =  1 30\n",
      "block, trial =  1 31\n",
      "block, trial =  1 32\n",
      "block, trial =  1 33\n",
      "block, trial =  1 34\n",
      "block, trial =  1 35\n",
      "block, trial =  1 36\n",
      "block, trial =  1 37\n",
      "block, trial =  1 38\n",
      "block, trial =  1 39\n",
      "block, trial =  1 40\n",
      "block, trial =  1 41\n",
      "block, trial =  1 42\n",
      "block, trial =  1 43\n",
      "block, trial =  1 44\n",
      "block, trial =  1 45\n",
      "block, trial =  1 46\n",
      "block, trial =  1 47\n",
      "block, trial =  1 48\n",
      "block, trial =  1 49\n",
      "block, trial =  1 50\n",
      "block, trial =  1 51\n",
      "block, trial =  1 52\n",
      "block, trial =  1 53\n",
      "block, trial =  1 54\n",
      "block, trial =  1 55\n",
      "block, trial =  1 56\n",
      "block, trial =  1 57\n",
      "block, trial =  1 58\n",
      "block, trial =  1 59\n",
      "block, trial =  1 60\n",
      "block, trial =  1 61\n",
      "block, trial =  1 62\n",
      "block, trial =  1 63\n",
      "block, trial =  1 64\n",
      "block, trial =  1 65\n",
      "block, trial =  1 66\n",
      "block, trial =  1 67\n",
      "block, trial =  1 68\n",
      "block, trial =  1 69\n",
      "block, trial =  1 70\n",
      "block, trial =  1 71\n",
      "block, trial =  1 72\n",
      "block, trial =  1 73\n",
      "block, trial =  1 74\n",
      "block, trial =  1 75\n",
      "block, trial =  1 76\n",
      "block, trial =  1 77\n",
      "block, trial =  1 78\n",
      "block, trial =  1 79\n",
      "block, trial =  1 80\n",
      "block, trial =  1 81\n",
      "block, trial =  1 82\n",
      "block, trial =  1 83\n",
      "block, trial =  1 84\n",
      "block, trial =  1 85\n",
      "block, trial =  1 86\n",
      "block, trial =  1 87\n",
      "block, trial =  1 88\n",
      "block, trial =  1 89\n",
      "block, trial =  1 90\n",
      "block, trial =  1 91\n",
      "block, trial =  1 92\n",
      "block, trial =  1 93\n",
      "block, trial =  1 94\n",
      "block, trial =  1 95\n",
      "block, trial =  1 96\n",
      "block, trial =  1 97\n",
      "block, trial =  1 98\n",
      "block, trial =  1 99\n",
      "block, trial =  1 100\n",
      "block, trial =  1 101\n",
      "block, trial =  1 102\n",
      "block, trial =  1 103\n",
      "block, trial =  1 104\n",
      "block, trial =  1 105\n",
      "block, trial =  1 106\n",
      "block, trial =  1 107\n",
      "block, trial =  1 108\n",
      "block, trial =  1 109\n",
      "block, trial =  1 110\n",
      "block, trial =  1 111\n",
      "block, trial =  1 112\n",
      "block, trial =  1 113\n",
      "block, trial =  1 114\n",
      "block, trial =  1 115\n",
      "block, trial =  1 116\n",
      "block, trial =  1 117\n",
      "block, trial =  1 118\n",
      "block, trial =  1 119\n",
      "block, trial =  1 120\n",
      "block, trial =  1 121\n",
      "block, trial =  1 122\n",
      "block, trial =  1 123\n",
      "block, trial =  1 124\n",
      "block, trial =  1 125\n",
      "block, trial =  1 126\n",
      "block, trial =  1 127\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py:682: RuntimeWarning: Mean of empty slice\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "block, trial =  1 128\n",
      "block, trial =  1 129\n",
      "block, trial =  1 130\n",
      "block, trial =  1 131\n",
      "block, trial =  1 132\n",
      "block, trial =  1 133\n",
      "block, trial =  1 134\n",
      "block, trial =  1 135\n",
      "block, trial =  1 136\n",
      "block, trial =  1 137\n",
      "block, trial =  1 138\n",
      "block, trial =  1 139\n",
      "block, trial =  1 140\n",
      "block, trial =  1 141\n",
      "block, trial =  1 142\n",
      "block, trial =  1 143\n",
      "block, trial =  1 144\n",
      "block, trial =  1 145\n",
      "block, trial =  1 146\n",
      "block, trial =  1 147\n",
      "block, trial =  1 148\n",
      "block, trial =  1 149\n",
      "block, trial =  1 150\n",
      "block, trial =  1 151\n",
      "block, trial =  1 152\n",
      "block, trial =  1 153\n",
      "block, trial =  1 154\n",
      "block, trial =  1 155\n",
      "block, trial =  1 156\n",
      "block, trial =  1 157\n",
      "block, trial =  1 158\n",
      "block, trial =  1 159\n",
      "block, trial =  1 160\n",
      "block, trial =  1 161\n",
      "block, trial =  1 162\n",
      "block, trial =  1 163\n",
      "block, trial =  1 164\n",
      "block, trial =  1 165\n",
      "block, trial =  1 166\n",
      "block, trial =  1 167\n",
      "block, trial =  1 168\n",
      "block, trial =  1 169\n",
      "block, trial =  1 170\n",
      "block, trial =  1 171\n",
      "block, trial =  1 172\n",
      "block, trial =  1 173\n",
      "block, trial =  1 174\n",
      "block, trial =  1 175\n",
      "block, trial =  1 176\n",
      "block, trial =  1 177\n",
      "block, trial =  1 178\n",
      "block, trial =  1 179\n",
      "block, trial =  1 180\n",
      "block, trial =  1 181\n",
      "block, trial =  1 182\n",
      "block, trial =  1 183\n",
      "block, trial =  1 184\n",
      "block, trial =  1 185\n",
      "block, trial =  1 186\n",
      "block, trial =  1 187\n",
      "block, trial =  1 188\n",
      "block, trial =  1 189\n",
      "block, trial =  1 190\n",
      "block, trial =  1 191\n",
      "block, trial =  1 192\n",
      "block, trial =  1 193\n",
      "block, trial =  1 194\n",
      "block, trial =  1 195\n",
      "block, trial =  1 196\n",
      "block, trial =  1 197\n",
      "block, trial =  1 198\n",
      "block, trial =  1 199\n",
      "block, trial =  2 0\n",
      "block, trial =  2 1\n",
      "block, trial =  2 2\n",
      "block, trial =  2 3\n",
      "block, trial =  2 4\n",
      "block, trial =  2 5\n",
      "block, trial =  2 6\n",
      "block, trial =  2 7\n",
      "block, trial =  2 8\n",
      "block, trial =  2 9\n",
      "block, trial =  2 10\n",
      "block, trial =  2 11\n",
      "block, trial =  2 12\n",
      "block, trial =  2 13\n",
      "block, trial =  2 14\n",
      "block, trial =  2 15\n",
      "block, trial =  2 16\n",
      "block, trial =  2 17\n",
      "block, trial =  2 18\n",
      "block, trial =  2 19\n",
      "block, trial =  2 20\n",
      "block, trial =  2 21\n",
      "block, trial =  2 22\n",
      "block, trial =  2 23\n",
      "block, trial =  2 24\n",
      "block, trial =  2 25\n",
      "block, trial =  2 26\n",
      "block, trial =  2 27\n",
      "block, trial =  2 28\n",
      "block, trial =  2 29\n",
      "block, trial =  2 30\n",
      "block, trial =  2 31\n",
      "block, trial =  2 32\n",
      "block, trial =  2 33\n",
      "block, trial =  2 34\n",
      "block, trial =  2 35\n",
      "block, trial =  2 36\n",
      "block, trial =  2 37\n",
      "block, trial =  2 38\n",
      "block, trial =  2 39\n",
      "block, trial =  2 40\n",
      "block, trial =  2 41\n",
      "block, trial =  2 42\n",
      "block, trial =  2 43\n",
      "block, trial =  2 44\n",
      "block, trial =  2 45\n",
      "block, trial =  2 46\n",
      "block, trial =  2 47\n",
      "block, trial =  2 48\n",
      "block, trial =  2 49\n",
      "block, trial =  2 50\n",
      "block, trial =  2 51\n",
      "block, trial =  2 52\n",
      "block, trial =  2 53\n",
      "block, trial =  2 54\n",
      "block, trial =  2 55\n",
      "block, trial =  2 56\n",
      "block, trial =  2 57\n",
      "block, trial =  2 58\n",
      "block, trial =  2 59\n",
      "block, trial =  2 60\n",
      "block, trial =  2 61\n",
      "block, trial =  2 62\n",
      "block, trial =  2 63\n",
      "block, trial =  2 64\n",
      "block, trial =  2 65\n",
      "block, trial =  2 66\n",
      "block, trial =  2 67\n",
      "block, trial =  2 68\n",
      "block, trial =  2 69\n",
      "block, trial =  2 70\n",
      "block, trial =  2 71\n",
      "block, trial =  2 72\n",
      "block, trial =  2 73\n",
      "block, trial =  2 74\n",
      "block, trial =  2 75\n",
      "block, trial =  2 76\n",
      "block, trial =  2 77\n",
      "block, trial =  2 78\n",
      "block, trial =  2 79\n",
      "block, trial =  2 80\n",
      "block, trial =  2 81\n",
      "block, trial =  2 82\n",
      "block, trial =  2 83\n",
      "block, trial =  2 84\n",
      "block, trial =  2 85\n",
      "block, trial =  2 86\n",
      "block, trial =  2 87\n",
      "block, trial =  2 88\n",
      "block, trial =  2 89\n",
      "block, trial =  2 90\n",
      "block, trial =  2 91\n",
      "block, trial =  2 92\n",
      "block, trial =  2 93\n",
      "block, trial =  2 94\n",
      "block, trial =  2 95\n",
      "block, trial =  2 96\n",
      "block, trial =  2 97\n",
      "block, trial =  2 98\n",
      "block, trial =  2 99\n",
      "block, trial =  2 100\n",
      "block, trial =  2 101\n",
      "block, trial =  2 102\n",
      "block, trial =  2 103\n",
      "block, trial =  2 104\n",
      "block, trial =  2 105\n",
      "block, trial =  2 106\n",
      "block, trial =  2 107\n",
      "block, trial =  2 108\n",
      "block, trial =  2 109\n",
      "block, trial =  2 110\n",
      "block, trial =  2 111\n",
      "block, trial =  2 112\n",
      "block, trial =  2 113\n",
      "block, trial =  2 114\n",
      "block, trial =  2 115\n",
      "block, trial =  2 116\n",
      "block, trial =  2 117\n",
      "block, trial =  2 118\n",
      "block, trial =  2 119\n",
      "block, trial =  2 120\n",
      "block, trial =  2 121\n",
      "block, trial =  2 122\n",
      "block, trial =  2 123\n",
      "block, trial =  2 124\n",
      "block, trial =  2 125\n",
      "block, trial =  2 126\n",
      "block, trial =  2 127\n",
      "block, trial =  2 128\n",
      "block, trial =  2 129\n",
      "block, trial =  2 130\n",
      "block, trial =  2 131\n",
      "block, trial =  2 132\n",
      "block, trial =  2 133\n",
      "block, trial =  2 134\n",
      "block, trial =  2 135\n",
      "block, trial =  2 136\n",
      "block, trial =  2 137\n",
      "block, trial =  2 138\n",
      "block, trial =  2 139\n",
      "block, trial =  2 140\n",
      "block, trial =  2 141\n",
      "block, trial =  2 142\n",
      "block, trial =  2 143\n",
      "block, trial =  2 144\n",
      "block, trial =  2 145\n",
      "block, trial =  2 146\n",
      "block, trial =  2 147\n",
      "block, trial =  2 148\n",
      "block, trial =  2 149\n",
      "block, trial =  2 150\n",
      "block, trial =  2 151\n",
      "block, trial =  2 152\n",
      "block, trial =  2 153\n",
      "block, trial =  2 154\n",
      "block, trial =  2 155\n",
      "block, trial =  2 156\n",
      "block, trial =  2 157\n",
      "block, trial =  2 158\n",
      "block, trial =  2 159\n",
      "block, trial =  2 160\n",
      "block, trial =  2 161\n",
      "block, trial =  2 162\n",
      "block, trial =  2 163\n",
      "block, trial =  2 164\n",
      "block, trial =  2 165\n",
      "block, trial =  2 166\n",
      "block, trial =  2 167\n",
      "block, trial =  2 168\n",
      "block, trial =  2 169\n",
      "block, trial =  2 170\n",
      "block, trial =  2 171\n",
      "block, trial =  2 172\n",
      "block, trial =  2 173\n",
      "block, trial =  2 174\n",
      "block, trial =  2 175\n",
      "block, trial =  2 176\n",
      "block, trial =  2 177\n",
      "block, trial =  2 178\n",
      "block, trial =  2 179\n",
      "block, trial =  2 180\n",
      "block, trial =  2 181\n",
      "block, trial =  2 182\n",
      "block, trial =  2 183\n",
      "block, trial =  2 184\n",
      "block, trial =  2 185\n",
      "block, trial =  2 186\n",
      "block, trial =  2 187\n",
      "block, trial =  2 188\n",
      "block, trial =  2 189\n",
      "block, trial =  2 190\n",
      "block, trial =  2 191\n",
      "block, trial =  2 192\n",
      "block, trial =  2 193\n",
      "block, trial =  2 194\n",
      "block, trial =  2 195\n",
      "block, trial =  2 196\n",
      "block, trial =  2 197\n",
      "block, trial =  2 198\n",
      "block, trial =  2 199\n"
     ]
    }
   ],
   "source": [
    "fit(3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FM\n",
      "block, trial =  0 0\n",
      "block, trial =  0 1\n",
      "block, trial =  0 2\n",
      "block, trial =  0 3\n",
      "block, trial =  0 4\n",
      "block, trial =  0 5\n",
      "block, trial =  0 6\n",
      "block, trial =  0 7\n",
      "block, trial =  0 8\n",
      "block, trial =  0 9\n",
      "block, trial =  0 10\n",
      "block, trial =  0 11\n",
      "block, trial =  0 12\n",
      "block, trial =  0 13\n",
      "block, trial =  0 14\n",
      "block, trial =  0 15\n",
      "block, trial =  0 16\n",
      "block, trial =  0 17\n",
      "block, trial =  0 18\n",
      "block, trial =  0 19\n",
      "block, trial =  0 20\n",
      "block, trial =  0 21\n",
      "block, trial =  0 22\n",
      "block, trial =  0 23\n",
      "block, trial =  0 24\n",
      "block, trial =  0 25\n",
      "block, trial =  0 26\n",
      "block, trial =  0 27\n",
      "block, trial =  0 28\n",
      "block, trial =  0 29\n",
      "block, trial =  0 30\n",
      "block, trial =  0 31\n",
      "block, trial =  0 32\n",
      "block, trial =  0 33\n",
      "block, trial =  0 34\n",
      "block, trial =  0 35\n",
      "block, trial =  0 36\n",
      "block, trial =  0 37\n",
      "block, trial =  0 38\n",
      "block, trial =  0 39\n",
      "block, trial =  0 40\n",
      "block, trial =  0 41\n",
      "block, trial =  0 42\n",
      "block, trial =  0 43\n",
      "block, trial =  0 44\n",
      "block, trial =  0 45\n",
      "block, trial =  0 46\n",
      "block, trial =  0 47\n",
      "block, trial =  0 48\n",
      "block, trial =  0 49\n",
      "block, trial =  0 50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py:682: RuntimeWarning: Mean of empty slice\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "block, trial =  0 51\n",
      "block, trial =  0 52\n",
      "block, trial =  0 53\n",
      "block, trial =  0 54\n",
      "block, trial =  0 55\n",
      "block, trial =  0 56\n",
      "block, trial =  0 57\n",
      "block, trial =  0 58\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2881, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-fe223a54f85a>\", line 1, in <module>\n",
      "  File \"<ipython-input-3-6c30869540d8>\", line 14, in fit\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py\", line 1582, in Fit_full\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py\", line 1370, in Fit_trial\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/lmfit/model.py\", line 873, in fit\n",
      "    output.fit(data=data, weights=weights)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/lmfit/model.py\", line 1216, in fit\n",
      "    self.init_fit = self.model.eval(params=self.params, **self.userkws)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/lmfit/model.py\", line 704, in eval\n",
      "    return self.func(**self.make_funcargs(params, kwargs))\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py\", line 787, in fct_velocity\n",
      "UnboundLocalError: local variable 'maxi' referenced before assignment\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1821, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnboundLocalError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1132, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 313, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 1453, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 1414, in getframeinfo\n",
      "    lines, lnum = findsource(frame)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 182, in findsource\n",
      "    lines = linecache.getlines(file, globals_dict)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2827, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_code\n",
      "    self.showtraceback()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1824, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1412, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1320, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1170, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1108, in format_exception_as_a_whole\n",
      "    records = self.get_records(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1147, in get_records\n",
      "    traceback.print_exc(file=self.ostream)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 159, in print_exc\n",
      "    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1821, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'error' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1132, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 313, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 1453, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/usr/lib/python3.5/inspect.py\", line 1414, in getframeinfo\n",
      "    lines, lnum = findsource(frame)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 182, in findsource\n",
      "    lines = linecache.getlines(file, globals_dict)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1015, in run\n",
      "    value = future.result()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/concurrent.py\", line 237, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 3, in raise_exc_info\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1021, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1015, in run\n",
      "    value = future.result()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/concurrent.py\", line 237, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 3, in raise_exc_info\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 285, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2717, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2846, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1824, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1412, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1320, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1189, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1108, in format_exception_as_a_whole\n",
      "    records = self.get_records(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1147, in get_records\n",
      "    traceback.print_exc(file=self.ostream)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 159, in print_exc\n",
      "    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/traitlets/config/application.py\", line 117, in format\n",
      "    return super(LevelFormatter, self).format(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 575, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 525, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 370, in dispatch_queue\n",
      "    yield self.process_one()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1015, in run\n",
      "    value = future.result()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/concurrent.py\", line 237, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 3, in raise_exc_info\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1021, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1015, in run\n",
      "    value = future.result()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/concurrent.py\", line 237, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 3, in raise_exc_info\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1021, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 269, in dispatch_shell\n",
      "    self.log.error(\"Exception in message handler:\", exc_info=True)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1308, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1415, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1425, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1487, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 855, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 986, in emit\n",
      "    self.handleError(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 908, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/traitlets/config/application.py\", line 117, in format\n",
      "    return super(LevelFormatter, self).format(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 575, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 525, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/ioloop.py\", line 604, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/ioloop.py\", line 619, in <lambda>\n",
      "    self.add_future(ret, lambda f: f.result())\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/concurrent.py\", line 237, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 3, in raise_exc_info\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/gen.py\", line 1021, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 372, in dispatch_queue\n",
      "    self.log.exception(\"Error in message handler\")\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1314, in exception\n",
      "    self.error(msg, *args, exc_info=exc_info, **kwargs)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1308, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1415, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1425, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1487, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 855, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 986, in emit\n",
      "    self.handleError(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 908, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 575, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 525, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 95, in updatecache\n",
      "    stat = os.stat(fullname)\n",
      "NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/ANEMO-0.0.1-py3.5.egg/ANEMO/ANEMO.py'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/runpy.py\", line 184, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/ioloop.py\", line 831, in start\n",
      "    self._run_callback(callback)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/ioloop.py\", line 621, in _run_callback\n",
      "    self.handle_callback_exception(callback)\n",
      "  File \"/home/drone/.local/lib/python3.5/site-packages/tornado/ioloop.py\", line 633, in handle_callback_exception\n",
      "    app_log.error(\"Exception in callback %r\", callback, exc_info=True)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1308, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1415, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1425, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 1487, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 855, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 986, in emit\n",
      "    self.handleError(record)\n",
      "  File \"/usr/lib/python3.5/logging/__init__.py\", line 908, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 100, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 487, in __init__\n",
      "    self._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 500, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 498, in _load_lines\n",
      "    frame.line\n",
      "  File \"/usr/lib/python3.5/traceback.py\", line 282, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/usr/lib/python3.5/linecache.py\", line 103, in updatecache\n",
      "    data = cache[filename][0]()\n",
      "zlib.error: Error -5 while decompressing data: incomplete or truncated stream\n"
     ]
    }
   ],
   "source": [
    "fit(4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fit(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fit(6)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fit(7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fit(8)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fit(9)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fit(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fit(11)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
